# Generated by Django 4.2.11 on 2024-05-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Logout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
