# Generated by Django 4.2.11 on 2024-05-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Logout', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
